### ISSUE TITLE
@Html.RenderFlashMessages() Not Working

### ISSUE THREAD

**Issue by odai-massar** [Vereyon/FlashMessage#1]
Hi

Thank you for providing this package.
I followed the documentation but the rendering method didn't work (Compilation error, no definition for 'RenderFlashMessages')

i tried this:

```
@Vereyon.Web.FlashMessageHtmlHelper.RenderFlashMessages(Html)
```

and it worked perfectly. any idea?

**Comment by cakkermans** [comment]
You probably forgot to import the Vereyon.Web namespace into your view. You can do this using the web.config file or using the @using directive in the Razor view. I'll add this to the documentation later.

**Comment by odai-massar** [comment]
Yes, i did... thank you
