### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by hey-red** [Vereyon/FlashMessage#11]
Seems like nuget packages is very old.

**Comment by cakkermans** [comment]
Well, not much has changed, so I see little reason to update them. Is there anything specific you are expecting to be updated? The packages do work, right?

**Comment by cakkermans** [comment]
There's a new release coming which unifies both the ASP.NET MVC Core and ASP.NET MVC versions. [Get the prerelease package](https://www.nuget.org/packages/Vereyon.Web.FlashMessage/1.1.0-beta1).
