### ISSUE TITLE
NullReferenceExceptiob:Object reference not setting an instance

### ISSUE THREAD

**Issue by askalito** [Vereyon/FlashMessage#20]
![16107012884399210109428296678844](https://user-images.githubusercontent.com/54416393/104704225-0dae5c00-5721-11eb-9841-f48d012154e7.jpg)
I am trying to use flash messages to give confirmation. I have followed what is written in the guilde but still getting the same error. 

The code that i uses to initalize flashmessages is below
![Uploading 16107014275552402156122941136339.jpg…]()

**Comment by cakkermans** [comment]
Hi @askalito, I am unable to reproduce your issue. Can I ask you a few things to narrow down the issue:

- Are you using version 2.0.0 of FlashMessage https://www.nuget.org/packages/Vereyon.Web.FlashMessage/2.0.0 ?
- Which version of .NET and ASP.NET are you using?
- Do other messages work, or does nothing of FlashMessage work?

**Comment by cakkermans** [comment]
I am closing this issue due to a lack of feedback.
