### ISSUE TITLE
Setting the cookie _FlashMessage with the flag secure

### ISSUE THREAD

**Issue by imranazad** [Vereyon/FlashMessage#22]
Is it a good idea to the set `secure` flag on the cookie `_FlashMessage` I can't see what security issues would result in not setting this flag as I understand it, it's just used to display messages to the user, however I can see if the messages are of a sensitive nature then we should ensure the cookie isn't passed over HTTP. I have noticed there are references in the code to stop "tampering" of the cookie which inclines me to believe this cookie should be set with the `secure` flag.

Any thoughts? @cakkermans @larikitty @odai-massar

**Comment by cakkermans** [comment]
Hi @imranazad, cookie security is indeed a valid point. It might contain sensitive information. This is however accounted for in the design of FlashMessage.

**FlashMessage 1.X** encodes the cookie by itself using the machine key. See:

```
public void Queue(IList<FlashMessageModel> messages)
{

    // Serialize and digitally sign the data.
    // Encoding/signing is done using the configured encryption and key in the machineKey element.
    // TODO: Replace with MachineKey.Protect for .Net Framework >= 4.5
    var serializedMessages = FlashMessage.Serialize(messages);
    var data = MachineKey.Encode(serializedMessages, MachineKeyProtection.All);  <--------------
```

**FlashMessage 2.X** uses the [built in ASP.NET Core TempData provider, which is encrypted](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0#tempdata-providers).

In case you still wish the control the details of the cookie used, you can do so while setting up your temp data provider, using the [CookieTempDataProviderOptions ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.cookietempdataprovideroptions?view=aspnetcore-5.0) class.

**Comment by imranazad** [comment]
@cakkermans Many thanks for the reply, since I can control the details of the cookies used I'll close this issue.
