### ISSUE TITLE
Make close icon configurable

### ISSUE THREAD

**Issue by jimSampica** [Vereyon/FlashMessage#23]
We use FontAwesome for close icons and it would be nice to replace `&times;` with the equivalent [FontAwesome times](https://fontawesome.com/icons/times) character

**Comment by cakkermans** [comment]
@jamesSampica, I have released a new version of the package, in which the FlashMessageTagHelper class is more extensible. To achieve your goal, you should override the `RenderBootstrap5DismissButton()` or `RenderBootstrap3DismissButton()` method, depending on what Twitter Bootstrap version you are using.

Let me know if that helps.
