### ISSUE TITLE
[Suggestion] Auto-dismiss

### ISSUE THREAD

**Issue by larikitty** [Vereyon/FlashMessage#3]
This is a suggestion: put an auto-dismiss time to alerts (configurable, of course).

**Comment by fdkdervis** [comment]
You can maybe use JavaScript to dismiss opens alerts

**Comment by larikitty** [comment]
> You can maybe use JavaScript to dismiss opens alerts

I already use this actually, even at the time of my suggestion. Tks.

**Comment by larikitty** [comment]
Closing this issue. @cakkermans already made this option: https://github.com/Vereyon/FlashMessage/issues/9#issuecomment-584363398
