### ISSUE TITLE
netcoreapp1.1 compatability?

### ISSUE THREAD

**Issue by PeterSawyer** [Vereyon/FlashMessage#6]
Can you update so we can run with latest.

```
ERROR: Package Microsoft.Web.Infrastructure 1.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Web.Infrastructure 1.0.0 supports: net40 (.NETFramework,Version=v4.0)

ERROR: One or more packages are incompatible with .NETCoreApp,Version=v1.1.

EXCEPTION: Package restore failed. Rolling back package changes for
```

**Comment by cakkermans** [comment]
I am working on .NET Core support. Due to the different architecture of ASP.NET Core a lot of code needs to be refactored. See https://github.com/Vereyon/FlashMessage/tree/master/Web.FlashMessage.MvcCoreExample for the current working core.

**Comment by cakkermans** [comment]
I just completed the release of the first ASP.NET Core version. See: https://www.nuget.org/packages/Web.FlashMessage.Core/1.0.0
