### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by martinRocks** [Vereyon/FlashMessage#7]
I'm using your nuget package in my MVC 5 app, however, I can't seem to write a unit test that mocks everything that is needed by "FlashMessage.Confirmation("Your data has been saved");".

Thanks

**Comment by cakkermans** [comment]
Mocking `IFlashMessageTransport` should do the trick. Make sure that you set the mock `IFlashMessageTransport` implementation as the transport to use a startup using:

`FlashMessage.Transport = yourMockTransport`

**Comment by cakkermans** [comment]
Closing this issue due to lack of feedback.
