### ISSUE TITLE
Dismiss icon should be configurable

### ISSUE THREAD

**Issue by richsage** [Vereyon/FlashMessage#9]
Not all flash messages require a dismiss icon. It would be great if this could be configurable to be shown/hidden on a per-message basis at the point of render.

**Comment by larikitty** [comment]
> Not all flash messages require a dismiss icon. It would be great if this could be configurable to be shown/hidden on a per-message basis at the point of render.

Hi @richsage! I've opened an [similar issue](https://github.com/Vereyon/FlashMessage/issues/3). We're thinking the same approach.

**Comment by cakkermans** [comment]
Hi @richsage and @larikitty, you are right. I made the dismiss icon optional. Please get the latest version of the package at https://www.nuget.org/packages/Vereyon.Web.FlashMessage/

You can now disable the dismiss icons using: `@Vereyon.Web.FlashMessageHtmlHelper.RenderFlashMessages(Html, false)`
